name: CNN

on:
  schedule:
    - cron: '0 0/3 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git pull
          git config --global user.email "your-email@example.com"
          git config --global user.name "cnn bot"
      
      - name: updating cnn
        run: |
          set -x  # Debugging aktivieren
          sh Stream/cnn.sh
        
      - name: git add
        run: |
          git add -A
          ls -la
          
      - name: commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin main
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Link updated"
            git push
