name: EuroStar

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "estar bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install requests module
        run: python3 -m pip install requests

      - name: Execute Python script
        run: python3 Stream/estar/estar.py > Stream/estar/estar.m3u8

      - name: git add
        run: |
          git add -A
          ls -la 

      - name: commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin main
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "estar updated"
            git push origin main
