name: nownew

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "nownew bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests

      - name: Install streamlink module from forked repository
        run: python3 -m pip install git+https://github.com/ipstreet312/streamlink

      - name: fetch content nownew
        run: |
          final_url=$(python3 ressources/nowtvtr.py)
          echo "erstrm=${final_url}" >> $GITHUB_ENV
          dastrm=$(echo $final_url | sed 's/nowtv-live-ad.ercdn.net\/nowtv\/playlist.m3u8/nowtv.daioncdn.net\/nowtv\/nowtv.m3u8/')
          dastrm=$(echo $dastrm | sed 's/resolution=640/resolution=1280/')
          echo "dastrm=${dastrm}" >> $GITHUB_ENV

      - name: Replace Text
        run: |
          erstrm=${erstrm}
          dastrm=${dastrm}
          sed -i "\|ercdn.net/nowtv| c $erstrm" playlist.m3u
          sed -i "\|daioncdn.net/nowtv| c $dastrm" playlist.m3u
          sed -i "\|ercdn.net/nowtv| c $erstrm" tmp/now.m3u8
          sed -i "\|daioncdn.net/nowtv| c $dastrm" tmp/now.m3u8

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin main
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit, ending workflow successfully."
            exit 0
          else
            git add playlist.m3u tmp/now.m3u8
            git commit -m "nownew updated"
            git push origin main
